# Generated by Django 5.0.6 on 2024-05-18 10:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customuser'),
        ('diary', '0003_alter_diary_author_alter_userrating_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='interest',
        ),
        migrations.AddField(
            model_name='customuser',
            name='user_interest',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
