# Generated by Django 4.2.11 on 2024-05-04 07:50

from django.db import migrations, models
import travel.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('province', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=15)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=travel.models.dest_pic_path)),
                ('popularity', models.IntegerField(blank=True, default=0)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2)),
                ('tags', models.TextField()),
            ],
        ),
    ]
