# Generated by Django 4.2.13 on 2024-05-24 19:06

import django.core.validators
from django.db import migrations, models
import travel.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('type', models.CharField(choices=[('s', '景区'), ('u', '学校')], default='s', max_length=1)),
                ('province', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=15)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to=travel.models.dest_pic_path)),
                ('popularity', models.IntegerField(blank=True, default=0)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0, message='Rating must be at least 0'), django.core.validators.MaxValueValidator(5, message='Rating cannot be greater than 5')])),
                ('mapjson', models.TextField(default='{}', help_text='请粘贴地图的json文字')),
                ('tags', models.ManyToManyField(to='travel.category')),
            ],
        ),
    ]
