# Generated by Django 4.2.11 on 2024-05-04 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='destination',
            name='tags',
        ),
        migrations.AddField(
            model_name='destination',
            name='tags',
            field=models.ManyToManyField(to='travel.category'),
        ),
    ]
