# Generated by Django 4.2.11 on 2024-05-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_category_remove_destination_tags_destination_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='mapjson',
            field=models.TextField(default='{}', help_text='请粘贴地图的json文字'),
        ),
    ]
