# Generated by Django 4.2.13 on 2024-05-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_remove_destination_image_destination_image_url_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='type',
            field=models.CharField(choices=[('s', '景区'), ('u', '学校')], default='s', max_length=1),
        ),
    ]
