# Generated by Django 4.2.11 on 2024-05-05 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_destination_mapjson'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='type',
            field=models.CharField(choices=[('u', '学校'), ('s', '景区')], default='s', max_length=1),
        ),
    ]
