# Generated by Django 4.2.11 on 2024-05-15 08:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_alter_destination_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2, validators=[django.core.validators.MinValueValidator(0, message='Rating must be at least 0'), django.core.validators.MaxValueValidator(5, message='Rating cannot be greater than 5')]),
        ),
        migrations.AlterField(
            model_name='destination',
            name='type',
            field=models.CharField(choices=[('u', '学校'), ('s', '景区')], default='s', max_length=1),
        ),
    ]
