# Generated by Django 4.2.13 on 2024-05-15 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0006_alter_destination_rating_alter_destination_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='type',
            field=models.CharField(choices=[('s', '景区'), ('u', '学校')], default='s', max_length=1),
        ),
    ]
