# Generated by Django 5.0.6 on 2024-05-18 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0007_alter_destination_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='type',
            field=models.CharField(choices=[('u', '学校'), ('s', '景区')], default='s', max_length=1),
        ),
    ]
