# Generated by Django 4.2.11 on 2024-05-02 14:37

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('province', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=15)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='data/img/destinations/')),
                ('popularity', models.IntegerField(blank=True, default=0)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2)),
                ('tags', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=50, null=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='data/img/avatars/')),
                ('interests', models.TextField(default='{}')),
            ],
        ),
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('popularity', models.IntegerField(blank=True, default=0)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='diary.user')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='diary.destination')),
            ],
        ),
    ]
