# Generated by Django 4.2.11 on 2024-05-04 07:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('travel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_time', models.DateTimeField(blank=True, default=django.utils.timezone.now)),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('popularity', models.IntegerField(blank=True, default=0)),
                ('rating', models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=2)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.user')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='travel.destination')),
            ],
        ),
    ]
